CREATE TABLE IF NOT EXISTS APEX_STRATEGY_TEST_STRATEGY_01 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    source_scanner_id INTEGER,
    symbol TEXT,
    price REAL,
    volume REAL,
    volatility REAL,
    session TEXT,
    scanned_at TEXT,
    scan_run_id TEXT,
    score REAL,
    candidate_status TEXT,
    trend TEXT,
    ema REAL,
    distance_to_ema REAL,
    is_premium_zone INTEGER,
    is_discount_zone INTEGER,
    is_equilibrium_zone INTEGER,
    bos INTEGER,
    choch INTEGER,
    liq_sweep INTEGER,
    fvg INTEGER,
    ob INTEGER,
    reason_tags TEXT,
    raw_json TEXT,

    strategy_name TEXT,
    strategy_status TEXT,
    copied_at TEXT,

    entry_price REAL,
    stop_loss REAL,
    take_profit_1 REAL,
    take_profit_2 REAL,
    take_profit_3 REAL,
    direction TEXT,
    trade_lifetime_min INTEGER,
    winrate REAL
);
