# config.py

MODE = "PAPER"  # SIMULATION / PAPER / LIVE

DEFAULT_BALANCE = 1000

EXCHANGE_NAME = "Bybit"
MARKET_TYPE = "Futures"

REQUIRE_API_FOR_LIVE = True
BLOCK_IF_NO_BALANCE = True
BLOCK_IF_RISK = True
